cargo-features = ["codegen-backend", "panic-immediate-abort"]

[package]
name = "fabsegame_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" , default-features = false, features = [
    "bevy_animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_image",
    "bevy_input_focus",
    "bevy_log",
    "bevy_render",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_window",
    "bevy_winit",
    "default_font",
    "multi_threaded",
    "std",
    "wayland",
    "webp",
    "flac"
] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }

[target.'cfg(all(target_family = "wasm", any(target_os = "unknown", target_os = "none")))'.dependencies]
getrandom = { version = "^0.3", features = ["wasm_js"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = [
    "bevy_animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_image",
    "bevy_input_focus",
    "bevy_log",
    "bevy_render",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_window",
    "bevy_winit",
    "default_font",
    "multi_threaded",
    "std",
    "webp",
    "flac",
    "webgpu", 
    "web"      
] }

[target.'cfg(target_arch = "windows")'.dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = [
    "bevy_animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_image",
    "bevy_input_focus",
    "bevy_log",
    "bevy_render",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_window",
    "bevy_winit",
    "default_font",
    "multi_threaded",
    "std",
    "webp",
    "flac",
] }

[profile.release]
codegen-units = 1
lto = "thin"
strip = true
panic = "immediate-abort"

[profile.dev]
panic = "immediate-abort"
debug = "line-tables-only"
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = true
lto = "thin"
panic = "immediate-abort"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"
absolute_paths = "warn"
allow_attributes = "warn"
arithmetic_side_effects = "warn"
as_conversions = "warn"
error_impl_error = "warn"
expect_used = "warn"
field_scoped_visibility_modifiers = "warn"
if_then_some_else_none = "warn"
implicit_clone = "warn"
indexing_slicing = "warn"
infinite_loop = "warn"
large_include_file = "warn"
mod_module_files = "warn"
panic = "warn"
panic_in_result_fn = "warn"
print_stdout = "warn"
redundant_type_annotations = "warn"
return_and_then = "warn"
str_to_string = "warn"
unneeded_field_pattern = "warn"
verbose_file_reads = "warn"
use_debug = "warn"
unwrap_used = "warn"
unwrap_in_result = "warn"
unused_trait_names = "warn"
unused_result_ok = "warn"
