on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Modify cargo config for CI
        run: |
          sed -i 's/rustflags = \["-Ctarget-cpu=native", "-Clink-arg=--ld-path=wild"\]/rustflags = ["-Ctarget-cpu=native, "-Clink-arg=--fuse-ld=mold"]/' .cargo/config.toml
      - name: Install dependencies
        run: sudo apt-get install -y mold clang
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          args: "--release"
          toolchain: "nightly"
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: space-invaders-remastered
          changes-file: "CHANGELOG.md"
          target: ${{ matrix.platform.target }}

